### $f(x,y)=3x^2y-y^3-3x^2-3y^2$
1. find its critical points
2. classify them

In [1]:
from IPython.display import YouTubeVideo
YouTubeVideo(id="shWXeUn5BHk", width=600, height=400)

In [1]:
import numpy as np
import ipyvolume as ipv
import ipyvolume.pylab as plt3d

X = np.arange(-10, 10, 0.1)  
Y = np.arange(-10, 10, 0.1)  
X, Y = np.meshgrid(X, Y) 
Z = 3*X**2*Y - Y**3 - 3*X**2 - 3*Y**2

plt3d.figure(screen_capture_enabled=True)

plt3d.plot_surface(X, Z, Y, color="green")
#ipv.quickscatter(1., 1., 0.)

plt3d.zlabel("y")
plt3d.ylabel("z")
plt3d.show()

### Symbolic solution

In [3]:
import sympy
sympy.init_printing()

x, y = sympy.symbols("x, y")
f = 3*x**2*y - y**3 - 3*x**2 - 3*y**2
f

**1.find its critical points**

In [4]:
f_grad = [f.diff(i) for i in (x,y)]
ciric_points = sympy.solve(f_grad, (x,y))
ciric_points

**2.classify its critical points using second derivative test**

In [5]:
f_hessian = [[f.diff(x_, y_) for x_ in (x, y)] for y_ in (x, y)]
f_hessian = sympy.Matrix(f_hessian)
hessian_det = f_hessian.det() # test fomular
hessian_det

In [6]:
ciric_points_dict = [{x:i[0], y:i[1]} for i in ciric_points]
sec_deriv_test = [hessian_det.subs(cp) for cp in ciric_points_dict]
sec_deriv_test

In [8]:
sec_deriv_test1 = np.array(sec_deriv_test)
ciric_points1 = np.array(ciric_points)
saddle_points = ciric_points1[np.where(sec_deriv_test1 < 0)]
local_points = ciric_points1[np.where(sec_deriv_test1 > 0)]
print("Saddle Points: {} \n Local maximum points: {}".format(saddle_points, local_points))

Saddle Points: [[0 -2]
 [-sqrt(3) 1]
 [sqrt(3) 1]] 
 Local maximum points: [[0 0]]


In [9]:
X = np.arange(-10, 10, 0.1)  
Y = np.arange(-10, 10, 0.1)  
X, Y = np.meshgrid(X, Y) 
Z = 3*X**2*Y - Y**3 - 3*X**2 - 3*Y**2

x_sad = saddle_points[:,0].astype(float)
y_sad = saddle_points[:,1].astype(float)
z_sad = 3*x_sad**2*y_sad - y_sad**3 - 3*x_sad**2 - 3*y_sad**2

plt3d.figure(screen_capture_enabled=True)
plt3d.scatter(x_sad, z_sad, y_sad, size=5, marker="sphere", color='blue')
plt3d.scatter(np.array([0.]), np.array([0.]), np.array([0.]), size=5, marker="diamond")
plt3d.plot_surface(X, Z, Y, color="green")

plt3d.zlabel("y")
plt3d.ylabel("z")
plt3d.show()

### Numerical solution

In [ ]:
from scipy import optimize

x, y = sympy.symbols("x, y")
f = 3*x**2*y - y**3 - 3*x**2 - 3*y**2
f_grad = [f.diff(i) for i in (x, y)]
f_hess = [[f.diff(i, j) for i in (x, y)] for j in (x, y)]

f_lamb = sympy.lambdify((x, y), f, 'numpy')
fgrad_lamb = sympy.lambdify((x, y), f_grad, 'numpy')
fhess_lamb = sympy.lambdify((x, y), f_hess, 'numpy')

In [23]:
def func_XY_to_X_Y(f):
    return lambda X: np.array(f(X[0], X[1]))

In [24]:
f1 = func_XY_to_X_Y(f_lamb)
f_grad1 = func_XY_to_X_Y(fgrad_lamb)
f_hess1 = func_XY_to_X_Y(fhess_lamb)

Newton’s method:

In [29]:
x_opt = optimize.fmin_ncg(f1, (0, 0), fprime=f_grad1, fhess=f_hess1)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 1
         Function evaluations: 2
         Gradient evaluations: 2
         Hessian evaluations: 1


In [30]:
x_opt

array([0., 0.])

quasi-Newton methods:

In [32]:
x_opt1 = optimize.fmin_bfgs(f1, (0, 0), fprime=f_grad1)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1


In [33]:
x_opt1

array([0, 0])

 conjugate-gradient methods:

In [35]:
x_opt2 = optimize.fmin_cg(f1, (0, 0), fprime=f_grad1)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1


In [36]:
x_opt2

array([0, 0])